## Copyright 2009-2022 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

set(DNNL_VERBOSE ON CACHE INTERNAL "")
set(DNNL_LIBRARY_NAME "dnnl" CACHE INTERNAL "")
set(DNNL_ENABLE_WORKLOAD "INFERENCE" CACHE INTERNAL "")
set(DNNL_ENABLE_PRIMITIVE "CONVOLUTION;POOLING;REORDER" CACHE INTERNAL "")
set(DNNL_ENABLE_PRIMITIVE_CPU_ISA "ALL" CACHE INTERNAL "")
set(DNNL_ENABLE_CONCURRENT_EXEC ON CACHE INTERNAL "")
set(DNNL_ENABLE_PRIMITIVE_CACHE ON CACHE INTERNAL "")
set(DNNL_USE_RT_OBJECTS_IN_PRIMITIVE_CACHE OFF CACHE INTERNAL "")
set(DNNL_ENABLE_MAX_CPU_ISA OFF CACHE INTERNAL "")
set(DNNL_ENABLE_CPU_ISA_HINTS OFF CACHE INTERNAL "")

set(DNNL_LIBRARY_TYPE "STATIC" CACHE INTERNAL "")
set(DNNL_BUILD_EXAMPLES OFF CACHE INTERNAL "")
set(DNNL_BUILD_TESTS OFF CACHE INTERNAL "")
set(DNNL_BUILD_FOR_CI OFF CACHE INTERNAL "")
set(DNNL_WERROR OFF CACHE INTERNAL "")
set(DNNL_TEST_SET "CI" CACHE INTERNAL "")
set(DNNL_INSTALL_MODE "DEFAULT" CACHE INTERNAL "")
set(DNNL_CODE_COVERAGE "OFF" CACHE INTERNAL "")
set(DNNL_DPCPP_HOST_COMPILER "DEFAULT" CACHE INTERNAL "")

set(DNNL_ARCH_OPT_FLAGS "" CACHE INTERNAL "")
set(DNNL_ENABLE_JIT_PROFILING OFF CACHE INTERNAL "")
set(DNNL_ENABLE_ITT_TASKS OFF CACHE INTERNAL "")

set(DNNL_CPU_RUNTIME "TBB" CACHE INTERNAL "")
set(_DNNL_TEST_THREADPOOL_IMPL "STANDALONE" CACHE INTERNAL "")
set(TBBROOT ${TBB_ROOT} CACHE INTERNAL "")
if(OIDN_DEVICE_SYCL)
  set(DNNL_GPU_RUNTIME "DPCPP" CACHE INTERNAL "")
else()
  set(DNNL_GPU_RUNTIME "NONE" CACHE INTERNAL "")
endif()
set(DNNL_GPU_VENDOR "INTEL" CACHE INTERNAL "")

set(BENCHDNN_USE_RDPMC OFF CACHE INTERNAL "")
set(DNNL_USE_CLANG_SANITIZER "" CACHE INTERNAL "")
set(DNNL_ENABLE_MEM_DEBUG OFF CACHE INTERNAL "")
set(DNNL_USE_CLANG_TIDY "NONE" CACHE INTERNAL "")
set(DNNL_ENABLE_STACK_CHECKER OFF CACHE INTERNAL "")

set(DNNL_BLAS_VENDOR "NONE" CACHE INTERNAL "")

set(DNNL_AARCH64_USE_ACL OFF CACHE INTERNAL "")

add_subdirectory(mkl-dnn)